server:
  port: 8087
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
zuul:
  routes:
    api:
      path: /api/**
      serviceId: eureka-client
    test:
      path: /baidu/**
      url: https://www.baidu.com