server:
  port: 8085
spring:
  application:
    name: eureka-consumer-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
feign:
  hystrix:
    enabled: true